server:
  port: 8086
  servlet:
    context-path: /api/v1

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/train_transaction_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
